"""add capital role and monthly cash flow to assets

Revision ID: 1152a14e9d55
Revises: 6721ea138cdf
Create Date: 2026-08-14 17:29:53.284630

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1152a14e9d55'
down_revision: str | None = '6721ea138cdf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - adjusted: existing rows need a
  # default or this NOT NULL column addition fails outright. ###
  op.add_column(
    'assets',
    sa.Column(
      'capital_role',
      sa.Enum('INCOME', 'NEUTRAL', 'DRAIN', name='capital_role', native_enum=False, length=10),
      nullable=False,
      server_default='NEUTRAL',
    ),
  )
  op.alter_column('assets', 'capital_role', server_default=None)
  op.add_column('assets', sa.Column('monthly_cash_flow', sa.Numeric(precision=14, scale=2), nullable=True))
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_column('assets', 'monthly_cash_flow')
  op.drop_column('assets', 'capital_role')
  # ### end Alembic commands ###
